global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'express-api'
    static_configs:
      - targets: ['express-api:3001']

  - job_name: 'influx'
    static_configs:
      - targets: ['influxdb:8086']
